version: '3.8'
services:
  score_service:
    build:
      context: ./score_service
    ports:
      - "5001:5001"
    networks:
      - app_network

  auth_service:
    build:
      context: ./auth_service
    ports:
      - "5002:5002"
    networks:
      - app_network

  composition_service:
    build:
      context: ./composition_service
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - app_network

  load_balancer:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
